---
- name: Replace default nginx page
  hosts: web
  become: yes
  vars:
    custom_message: "<p><script> document.write(new Date().toLocaleDateString()); </script></p>"

  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Replace default page content
      lineinfile:
        path: /var/www/html/index.html
        regexp: '<h1>Welcome to nginx!</h1>'
        line: '<p>{{custom_message}}</p>'
        backup: yes
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
