---

services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  builder:
    image: maven:3.8.5-eclipse-temurin-8-alpine
    working_dir: /app
    command: sh -c "
      apk add --no-cache git &&
      git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git project &&
      cd project &&
      mvn -B clean package &&
      cp target/*.war /output/ "
    volumes:
     - build_artifacts:/output

  prod:
    image: tomcat:7-jre6
    depends_on:
      db:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - build_artifacts:/usr/local/tomcat/webapps
    environment:
      DB_IP: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DB}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  build_artifacts:
  mysql_data:
...